SELECT CONCAT(NAME,'(', SUBSTRING(OCCUPATION, 1, 1), ')') AS NAMEX
FROM OCCUPATIONS
ORDER BY NAMEX;

SELECT CONCAT("There are a total of ",COUNT(NAME), " ", LOWER(OCCUPATION),'s.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(NAME) ASC, OCCUPATION ASC;
